from .ebs.ebs import *
from .ecr.ecr import *
from .lambdafunction.lambdafunction import *
from .ec2.ec2 import *
from .rds.rds import *
from .s3.s3 import *
from .rekognition.rekognition import *
from .sqs.sqs import *
from .redshift.redshift import *
from .kinesis.kinesis import *
from .ecs.ecs import *
from .routetable.routetable import *
from .efs.efs import *
from .workspaces.workspaces import *
from .xray.xray import *
from .eks.eks import *
from .dynamodb.dynamodb import *
from .account.account import *
from .organizations.organizations import *
from .amplify.amplify import *
from .elb.elb import *
from .internetgateway.internetgateway import *
from .acl.acl import *
from .storagegateway.storagegateway import *
from .eip.eip import *
from .eni.eni import *
from .natgateway.natgateway import *
from .securitygroup.securitygroup import *
from .vpc.vpc import *
from .elbv2.elbv2 import *
from .elasticache.elasticache import *
from .apigateway.apigateway import *
# from .amplifyuibuilder.amplifyuibuilder import *
from .appstream.appstream import *
from .amp.amp import *
from .appintegrations.appintegrations import *
from .application_insights.application_insights import *
from .sns.sns import *
from .networkfirewall.netoworkfirewall import *
from .autoscaling.autoscaling import *
from .arc_zonal_shift.arc_zonal_shift import *
from .athena.athena import *
from .appsync.appsync import *
from .applicationcostprofiler.applicationcostprofiler import *
from .apprunner.apprunner import *
from .alexaforbusiness.alexaforbusiness import *
from .acm_pca.acm_pca import *
from .cloudformation.cloudformation import *
from .elasticbeanstalk.elasticbeanstalk import *
from .workspaces_thinclient.workspaces_thinclient import *
from .wisdom.wisdom import *
from .wafv2.wafv2 import *
from .emr.emr import *
from .appconfig.appconfig import *
from .waf.waf import *
from .vpclattice.vpclattice import *
from .acm.acm import *
from .route53.route53 import *
from .accessanalyzer.accessanalyzer import *
from .timestreamwrite.timestreamwrite import *
from .voiceid.voiceid import *
from .appmesh.appmesh import *
from .appflow.appflow import *
from .applicationautoscaling.applicationautoscaling import *
from .apigatewayv2.apigatewayv2 import *
from .wellarchitected.wellarchitected import *

