from modules.API.APIGateway.apigateway import *
from modules.API.AppSync.appsync import *
from modules.Applications.Amplify.amplify import *
from modules.Applications.Appflow.appflow import *
from modules.Applications.AppIntegrations.appintegrations import *
from modules.Applications.ApplicationAutoScaling.applicationautoscaling import *
from modules.Applications.ApplicationCostProfiler.applicationcostprofiler import *
from modules.Applications.ApplicationDiscoveryService.applicationdiscoveryservice import *
from modules.Billing.CapacityReservations.capacityreservations import *
from modules.Billing.Reservations.reservations import *
from modules.Billing.SavingsPlans.savingsplans import *
from modules.Compute.AppConfig.appconfig import *
from modules.Compute.AppStream.appstream import *
from modules.Compute.AutoScaling.autoscaling import *
from modules.Compute.Batch.batch import *
from modules.Compute.EBS.ebs import *
from modules.Compute.EC2.ec2 import *
from modules.Compute.ElasticBeanstalk.elasticbeanstalk import *
from modules.Compute.EMR.emr import *
from modules.Compute.Functions.functions import *
from modules.Compute.Snapshots.snapshot import *
from modules.Compute.SSM.ssm import *
from modules.Compute.Workspaces.workspaces import *
from modules.Containers.AppMesh.appmesh import *
from modules.Containers.AppRunner.apprunner import *
from modules.Containers.ECR.ecr import *
from modules.Containers.ECS.ecs import *
from modules.Containers.EKS.eks import *
from modules.Databases.Athena.athena import *
from modules.Databases.DocDB.docdb import *
from modules.Databases.DMS.dms import *
from modules.Databases.DynamoDB.dynamodb import *
from modules.Databases.ElastiCache.elasticache import *
from modules.Databases.MemoryDB.memorydb import *
from modules.Databases.Neptune.neptune import *
from modules.Databases.RDS.rds import *
from modules.Databases.Redshift.redshift import *
from modules.Databases.Keyspaces.keyspace import *
from modules.Databases.Timestream.timestream import *
from modules.MachineLearning.MWAA.mwaa import *
from modules.MachineLearning.ElasticSearch.elasticsearch import *
from modules.MachineLearning.Kendra.kendra import *
from modules.MachineLearning.OpenSearch.opensearch import *
from modules.MachineLearning.Rekognition.rekognition import *
from modules.MachineLearning.SageMaker.sagemaker import *
from modules.MachineLearning.Wisdom.wisdom import *
from modules.Management.accessanalyzer.accessanalyzer import *
from modules.Management.account.account import *
from modules.Management.accounts.accounts import *
from modules.Management.auditmanager.auditmanager import *
from modules.Management.cloudformation.cloudformation import *
from modules.Management.logs.logs import *
from modules.Management.organizations.organizations import *
from modules.Management.wellarchitected.wellarchitected import *
from modules.Management.support.support import *
from modules.Messaging.Firehose.firehose import *
from modules.Messaging.Kafka.kafka import *
from modules.Messaging.Kinesis.kinesis import *
from modules.Messaging.MQ.mq import *
from modules.Messaging.SES.ses import *
from modules.Messaging.SMS.sms import *
from modules.Messaging.SNS.sns import *
from modules.Messaging.SQS.sqs import *
from modules.Monitoring.AMP.amp import *
from modules.Monitoring.ApplicationInsights.application_insights import *
from modules.Monitoring.XRay.xray import *
from modules.Networking.ACL.acl import *
from modules.Networking.Arc_Zonal_Shift.arc_zonal_shift import *
from modules.Networking.CloudFront.cloudfront import *
from modules.Networking.DirectConnect.directconnect import *
from modules.Networking.EIP.eip import *
from modules.Networking.ELB.elb import *
from modules.Networking.ENI.eni import *
from modules.Networking.GlobalAccelerators.globalaccelerator import *
from modules.Networking.InternetGateway.internetgateway import *
from modules.Networking.NATGateway.natgateway import *
from modules.Networking.NetworkFirewall.networkfirewall import *
from modules.Networking.Route53.route53 import *
from modules.Networking.RouteTable.routetable import *
from modules.Networking.TransitGateway.transitgateway import *
from modules.Networking.VPC.vpc import *
from modules.Networking.VPN.vpn import *
from modules.Other.alexaforbusiness.alexaforbusiness import *
from modules.Other.snowball.snowball import *
from modules.Other.timestreamwrite.timestreamwrite import *
from modules.Other.translate.translate import *
from modules.Other.voiceid.voiceid import *
from modules.Security.ACM.acm import *
from modules.Security.ACM_PCA.acm_pca import *
from modules.Security.CloudHSM.cloudhsm import *
from modules.Security.SecurityGroup.securitygroup import *
from modules.Security.Shield.shield import *
from modules.Security.WAF.waf import *
from modules.Security.Secrets.secret import *
from modules.Storage.DLM.dlm import *
from modules.Storage.DataSync.datasync import *
from modules.Storage.EFS.efs import *
from modules.Storage.FSx.fsx import *
from modules.Storage.S3.s3 import *
from modules.Storage.StorageGateway.storagegateway import *
from modules.Storage.TransferFamily.transferfamily import *
